### ISSUE TITLE
Cassiopeia Q

### ISSUE THREAD

**Issue by Petrischale** [Feez/EvadeIssues#16]
Let's me step back inside when hovering over the field with my mouse.

**Comment by Feez** [comment]
Is this for Cassiopeia W with the field?

**Comment by Petrischale** [comment]
No, I do mean the Q. If I try to move exactly where her Q should appear, it first dodges but then steps back inside it.
I think leaving Cassiopeia W as a steppable field is fine, coz often it's beneficial to walk through it.

Seems like the delay of making the field safe again is kinda off ? Don't nail me on that one though haha

**Comment by Feez** [comment]
Yeah it would likely be the delay, though technically can be radius too. I’ll check it out

**Comment by Feez** [comment]
Fixed next update
