### ISSUE TITLE
Jhin R

### ISSUE THREAD

**Issue by Petrischale** [Feez/EvadeIssues#34]
Length might be off by a few units, seems to stop dodging when veeery close to the edge of his Ult drawing.

**Comment by Petrischale** [comment]
Actually, it seems like just the last shot is NOT getting registered. Maybe due to FOW though I don't know.

**Comment by Feez** [comment]
> Actually, it seems like just the last shot is NOT getting registered. Maybe due to FOW though I don't know.

This was correct. Fixed in beta
