### ISSUE TITLE
Veigar E

### ISSUE THREAD

**Issue by Petrischale** [Feez/EvadeIssues#6]
I tried on Veigar vs Diana - She'll autoattack just fine when not inside the cage. Once he moves up the cage around you - even if you're completely centered - it won't autoattack veigar. Once the cage is gone - back to AA. Seems like it's always evading even though it's safe.

**Comment by Feez** [comment]
https://dl.dropboxusercontent.com/s/lttreu5b4np6fpv/gfZXBhcByj.mp4

Fixed in next update ;)
